stages:
  - build
  - test
  - deploy

build_job:
  stage: build
  script:
    - $PROJECT_ROOT/bin/build.sh
  artifacts:
    paths:
      - .bundle/
      - vendor/bundle/

test_job:
  stage: test
  script:
    - $PROJECT_ROOT/bin/test.sh

deploy_dev:
  environment:
    name: development
    url: https://file-tracker-dev.lib.duke.edu/
  stage: deploy
  script:
    - $PROJECT_ROOT/bin/deploy.sh $CI_PROJECT_DIR
  after_script:
    - $PROJECT_ROOT/bin/after_deploy.sh
  only:
    - develop
  tags:
    - development

deploy_prod:
  environment:
    name: production
    url: https://file-tracker.lib.duke.edu/
  stage: deploy
  when: manual
  script:
    - $PROJECT_ROOT/bin/deploy.sh $CI_PROJECT_DIR
  after_script:
    - $PROJECT_ROOT/bin/after_deploy.sh
  only:
    - master
  tags:
    - production
