test:
  stage: test
  variables:
    RAILS_ENV: test
  script:
    - export
    - whoami
    - pwd
    - scl enable $RH_RUBY_VERSION -- gem install bundler --no-doc
    - scl enable $RH_RUBY_VERSION -- bundle install --deployment --binstubs --without production
    - scl enable $RH_RUBY_VERSION -- bundle exec rake db:setup
    - scl enable $RH_RUBY_VERSION -- bundle exec rake

develop:
  environment:
    name: development
    url: https://file-tracker-dev.lib.duke.edu/
  stage: deploy
  variables:
    RAILS_ENV: production
  script:
    - export
    - whoami
    - pwd
    - EXCLUDE=($EXCLUDE_FILES)
    - 'rsync -rv --delete ${EXCLUDE[@]/#/--exclude=} . $RAILS_ROOT'
    - cd $RAILS_ROOT
    - pwd
    - scl enable $RH_RUBY_VERSION -- bundle install --deployment --binstubs --clean --without development test
    - sudo -u $RAILS_USER -i rake -f $RAILS_ROOT/Rakefile $RAKE_TASKS
    - sudo systemctl restart puma.service
    - sudo systemctl restart resque-pool.service
  only:
    - develop
  tags:
    - development
