test:
  stage: test
  variables:
    RAILS_ENV: test
  script:
    - export
    - whoami
    - pwd
    - scl enable $RH_RUBY_VERSION -- gem install bundler --no-doc
    - scl enable $RH_RUBY_VERSION -- bundle install --deployment --binstubs --without production
    - scl enable $RH_RUBY_VERSION -- bundle exec rake db:setup
    - scl enable $RH_RUBY_VERSION -- bundle exec rake

develop:
  environment:
    name: development
    url: https://file-tracker-dev.lib.duke.edu/
  stage: deploy
  variables:
    RAILS_ENV: production
    RAKE_TASKS: "db:migrate db:seed assets:clean assets:precompile tmp:cache:clear"
    EXCLUDE_FILES: "/.bundle/ /.git/ /config/application.yml /log /tmp /public/assets/ /vendor/bundle/"
  script:
    - export
    - whoami
    - pwd
    - EXCLUDE=($EXCLUDE_FILES)
    - 'rsync -rv --delete ${EXCLUDE[@]/#/--exclude=} . $RAILS_ROOT'
    - cd $RAILS_ROOT
    - pwd
    - 'scl enable $RH_RUBY_VERSION "RAILS_ENV=$RAILS_ENV bundle install --deployment --binstubs --clean --without development test"'
    - 'sudo -u $RAILS_USER scl enable $RH_RUBY_VERSION "RAILS_ENV=$RAILS_ENV rake $RAKE_TASKS"'
    - sudo systemctl restart puma.service
    - sudo systemctl restart resque-pool.service
  only:
    - develop
  tags:
    - development
