test:
  stage: test
  variables:
    RAILS_ENV: test
  script:
    - scl enable rh-ruby24 -- bundle install --deployment --without production
    - scl enable rh-ruby24 -- bundle exec rake db:setup
    - scl enable rh-ruby24 -- bundle exec rake

develop:
  stage: deploy
  script:
    - /srv/perkins/bin/deploy-file-tracker.sh
  only:
    - develop
  tags:
    - development
