test:
  stage: test
  variables:
    RAILS_ENV: test
  script:
    - whoami
    - pwd
    - scl enable $RH_RUBY_VERSION $PROJECT_ROOT/bin/test.sh

develop:
  environment:
    name: development
    url: https://file-tracker-dev.lib.duke.edu/
  stage: deploy
  variables:
    RAILS_ENV: production
  script:
    - whoami
    - pwd
    - scl enable $RH_RUBY_VERSION $PROJECT_ROOT/bin/deploy.sh
  after_script:
    - sudo systemctl reload httpd.service
    - sudo systemctl restart resque-pool.service
  only:
    - develop
  tags:
    - development
