test:
  stage: test
  script:
    - whoami
    - pwd
    - export
    - $PROJECT_ROOT/bin/test.sh
develop:
  environment:
    name: development
    url: https://file-tracker-dev.lib.duke.edu/
  stage: deploy
  script:
    - whoami
    - pwd
    - $PROJECT_ROOT/bin/deploy.sh $CI_PROJECT_DIR
  after_script:
    - $PROJECT_ROOT/bin/after_deploy.sh
  only:
    - develop
  tags:
    - development
