default: &default
  adapter: mysql2
  username: file_tracker

development:
  <<: *default
  database: file_tracker_dev
  password: s3cret

test:
  <<: *default
  database: file_tracker_test
  password: s3cret

production:
  <<: *default
  database: file_tracker
