development:
  adapter: sqlite3
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000
  database: db/development.sqlite3
  
test:
  adapter: sqlite3
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000
  database: db/test.sqlite3

production:
  adapter: mysql2
  encoding: utf8
  database: <%= ENV.fetch("FILE_TRACKER_DB_NAME") { "file_tracker" } %>
  pool: 5
  host: 127.0.0.1
  port: 3306
  username: <%= ENV["FILE_TRACKER_DB_USER"] %>
  password: <%= ENV["FILE_TRACKER_DB_PASS"] %>
